# Site settings
title: Transcend
email: transcenduw@gmail.com
description: > # Transcend Engineering is a student organization dedicated to
  inspiring, facilitating, and developing student innovations.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://transcend.engineering" # the base hostname & protocol for your site
twitter_username: witranscend
github_username:  transcend-engineering
facebook_username: transcendwi
email_address: transcenduw@gmail.com
sass:
  sass_dir: _sass
  style: compressed
# Build settings
markdown: kramdown
